# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  portalProj: '**/FunctionSandbox.Portal/FunctionSandbox.Portal.csproj'
  functionsProj: '**/FunctionSandbox.Functions/FunctionSandbox.Functions.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

# dotnet publish ./FunctionSandbox.Portal/FunctionSandbox.Portal.csproj -c Release -o ./FunctionSandbox.Portal/publish
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: 'sdvfsdf'
    configuration: Release
    modifyOutputPath: '$(build.artifactStagingDirectory)\WebApp.zip'
    zipAfterPublish: true
    workingDirectory: '$(portalProj)'
    

-# task: VSBuild@1
 # inputs:
 #   solution: '$(portalProj)'
 #   msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
 #   platform: '$(buildPlatform)'
 #   configuration: '$(buildConfiguration)'

- task: AzureFileCopy@4
  inputs:
    sourcePath: '$(build.artifactStagingDirectory)\WebApp.zip'
    azureSubscription: 'Azure Function Sandbox'
    destination: 'AzureBlob'
    storage: 'functionsandboxrepo'
    ContainerName: 'deploy'


- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
